ALTER TABLE sync_tasks ADD COLUMN tg_chat_id INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sync_tasks ADD COLUMN max_chat_id INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sync_tasks ADD COLUMN error TEXT NOT NULL DEFAULT '';
