ALTER TABLE sync_tasks ADD COLUMN IF NOT EXISTS tg_chat_id BIGINT NOT NULL DEFAULT 0;
ALTER TABLE sync_tasks ADD COLUMN IF NOT EXISTS max_chat_id BIGINT NOT NULL DEFAULT 0;
ALTER TABLE sync_tasks ADD COLUMN IF NOT EXISTS error TEXT NOT NULL DEFAULT '';
